import FWCore.ParameterSet.Config as cms

process = cms.Process("Demo")

process.load('FWCore.MessageService.MessageLogger_cfi')
process.options   = cms.untracked.PSet( wantSummary = cms.untracked.bool(True) )
process.load('Configuration.StandardSequences.Services_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
from Configuration.PyReleaseValidation.autoCond import autoCond
process.GlobalTag.globaltag = cms.string( autoCond[ 'startup' ] )

process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )

process.source = cms.Source("PoolSource",
    # replace 'myfile.root' with the source file you want to use
    fileNames = cms.untracked.vstring(

'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_144_1_Sto.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_234_1_k0J.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_324_1_Jcn.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_54_1_Lqt.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_145_1_0xK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_235_1_m4l.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_325_1_WXq.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_55_1_UMg.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_146_1_VXe.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_236_1_NL5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_326_1_XXA.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_56_1_nbB.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_147_1_8Fp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_237_1_6EK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_327_1_BXD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_57_1_zpM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_148_1_xzL.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_238_1_QkF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_328_1_Oto.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_58_1_xU4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_149_1_fYT.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_239_1_O99.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_329_1_Y5w.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_59_1_9qD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_150_1_DDs.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_240_1_DOR.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_330_1_A1G.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_60_1_Ry5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_151_1_v0L.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_241_1_aPy.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_331_1_xNQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_61_1_I11.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_15_1_NzU.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_24_1_SMu.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_33_1_Pd9.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_6_1_Ufw.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_152_1_PfE.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_242_1_Vba.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_332_1_nux.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_62_1_sFx.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_153_1_99j.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_243_1_Ty2.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_333_1_XUS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_63_1_2YV.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_154_1_u2h.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_244_1_BYc.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_334_1_Apw.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_64_1_clf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_155_1_rCu.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_245_1_Mrl.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_335_1_I8J.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_65_1_vlh.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_156_1_NEM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_246_1_vHI.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_336_1_HlC.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_66_1_pmD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_157_1_NiG.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_247_1_gNe.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_337_1_GXi.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_67_1_L4y.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_158_1_ScM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_248_1_9Gn.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_338_1_AjD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_68_1_XCc.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_159_1_cY8.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_249_1_dFE.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_339_1_TLH.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_69_1_3rz.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_160_1_a6o.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_250_1_as4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_340_1_XAs.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_70_1_owv.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_161_1_VeQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_251_1_XaA.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_341_1_NZ9.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_71_1_LSb.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_16_1_6Df.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_25_1_Oi2.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_34_1_MIb.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_7_1_PEj.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_162_1_WTa.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_252_1_jMp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_342_1_mdt.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_72_1_5ai.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_163_1_rug.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_253_1_RaO.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_343_1_9Vm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_73_1_G9a.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_164_1_PlC.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_254_1_t6s.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_344_1_IwH.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_74_1_o3S.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_165_1_ZBK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_255_1_0yX.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_345_1_KdC.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_75_1_KrI.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_166_1_ICY.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_256_1_nni.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_346_1_AHu.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_76_1_9U5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_167_1_CQa.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_257_1_RKF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_347_1_aUp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_77_1_AZV.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_168_1_5F5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_258_1_93w.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_348_1_p57.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_78_1_4PW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_169_1_f0K.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_259_1_gmb.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_349_1_bbA.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_79_1_EdF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_170_1_eFF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_260_1_Oto.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_350_1_dxb.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_80_1_VXT.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_171_1_5NS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_261_1_qcT.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_351_1_qwg.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_81_1_HKv.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_17_1_Kr8.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_26_1_6ON.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_35_1_tIW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_8_1_xBK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_172_1_bxb.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_262_1_rmS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_352_1_e4y.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_82_1_QNl.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_173_1_Ba6.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_263_1_0rM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_353_1_Hi3.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_83_1_t39.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_174_1_tGR.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_264_1_IA1.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_354_1_JIq.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_84_1_IzF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_175_1_d0c.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_265_1_pkM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_355_1_DUc.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_85_1_p8o.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_176_1_Kgp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_266_1_qfh.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_356_1_hfs.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_86_1_w6R.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_177_1_R9b.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_267_1_EPL.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_357_1_rh5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_87_1_X2S.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_178_1_l50.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_268_1_keK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_358_1_ODQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_88_1_BPf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_179_1_3aD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_269_1_6vS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_359_1_wiw.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_89_1_ALi.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_180_1_yn8.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_270_1_cZS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_360_1_QzW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_90_1_PSN.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_181_1_j52.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_271_1_Jpz.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_36_1_0dN.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_91_1_j0L.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_18_1_BNG.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_27_1_ejn.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_361_1_HHe.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_9_1_wgq.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_182_1_vfn.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_272_1_w6o.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_362_1_eep.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_92_1_axD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_183_1_X89.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_273_1_0bg.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_363_1_6Dc.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_93_1_qhl.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_184_1_gdW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_274_1_APD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_364_1_PMT.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_94_1_CuF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_185_1_g3a.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_275_1_Uni.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_365_1_Ds9.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_95_1_gkW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_186_1_pXb.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_276_1_O9h.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_366_1_Emv.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_96_1_xRP.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_187_1_B6i.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_277_1_mWM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_367_1_vOm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_97_1_Xi2.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_188_1_SfI.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_278_1_XMo.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_368_1_2TR.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_98_1_b4t.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_189_1_PsN.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_279_1_s9H.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_369_1_e9R.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_99_1_epp.root',
    )
)

process.particleListDrawer = cms.EDAnalyzer("ParticleListDrawer",
    	printOnlyHardInteraction = cms.untracked.bool(True),
    	maxEventsToPrint = cms.untracked.int32(-1),
    	src = cms.InputTag('genParticles')
  )

process.demoWH = cms.EDFilter("GenFilter",
	genParticles = cms.untracked.InputTag('genParticles'),
	#particles = cms.untracked.vdouble(24, -24),
	process = cms.untracked.int32(1),
    	filter = cms.bool(False)
)

process.demoTTH = cms.EDFilter("GenFilter",
	genParticles = cms.untracked.InputTag('genParticles'),
	#particles = cms.untracked.vdouble(6, -6),
	process = cms.untracked.int32(3),
    	filter = cms.bool(False)
)

process.demoZH = cms.EDFilter("GenFilter",
	genParticles = cms.untracked.InputTag('genParticles'),
	#particles = cms.untracked.vdouble(23),
	process = cms.untracked.int32(2),
    	filter = cms.bool(False)
)


process.p1 = cms.Path(process.demoWH
		     #* process.particleListDrawer
		     )

process.p2 = cms.Path(process.demoTTH 
		     #* process.particleListDrawer
		     )

process.p3 = cms.Path(process.demoZH
		     #* process.particleListDrawer
		     )

