import FWCore.ParameterSet.Config as cms

process = cms.Process("Demo")

process.load('FWCore.MessageService.MessageLogger_cfi')
process.options   = cms.untracked.PSet( wantSummary = cms.untracked.bool(True) )
process.load('Configuration.StandardSequences.Services_cff')
process.load('Configuration.StandardSequences.FrontierConditions_GlobalTag_cff')
from Configuration.PyReleaseValidation.autoCond import autoCond
process.GlobalTag.globaltag = cms.string( autoCond[ 'startup' ] )

process.maxEvents = cms.untracked.PSet( input = cms.untracked.int32(-1) )

process.source = cms.Source("PoolSource",
    # replace 'myfile.root' with the source file you want to use
    fileNames = cms.untracked.vstring(

'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_100_1_no4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_190_1_2qJ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_280_1_il5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_370_1_sMr.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_101_1_iPF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_191_1_GO5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_281_1_OBt.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_371_1_63d.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_10_1_Ev7.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_19_1_rWV.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_28_1_2ih.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_37_1_Nm7.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_102_1_LFv.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_192_1_pU2.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_282_1_6hm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_372_1_y5n.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_103_1_FUI.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_193_1_nUn.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_283_1_cmv.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_373_1_AeA.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_104_1_8r7.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_194_1_0Le.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_284_1_cJ4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_374_1_bkv.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_105_1_gfd.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_195_1_YMU.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_285_1_dtE.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_375_1_zY0.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_106_1_qIG.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_196_1_SlF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_286_1_8lY.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_376_1_bym.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_107_1_3Qk.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_197_1_Jcs.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_287_1_Bmf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_377_1_5kQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_108_1_JWR.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_198_1_eQ6.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_288_1_psL.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_378_1_BJN.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_109_1_cSe.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_199_1_C1D.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_289_1_iEx.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_379_1_BjQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_110_1_UA1.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_200_1_nrH.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_290_1_jr6.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_380_1_SY1.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_111_1_OGR.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_201_1_ImH.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_291_1_cRK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_381_1_qNJ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_11_1_Hyw.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_20_1_gO2.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_29_1_H0L.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_38_1_ZBk.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_112_1_YYI.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_202_1_pG1.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_292_1_7FQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_382_1_0YM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_113_1_nsW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_203_1_1hQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_293_1_tWF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_383_1_v2u.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_114_1_YCx.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_204_1_gxm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_294_1_1rm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_384_1_rcE.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_115_1_Mc5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_205_1_UVw.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_295_1_Ee5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_385_1_xBZ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_116_1_irF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_206_1_K92.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_296_1_uU1.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_386_1_D5F.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_117_1_p2C.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_207_1_kUq.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_297_1_kmE.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_387_1_z7j.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_118_1_5TJ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_208_1_0a9.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_298_1_hj2.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_388_1_Koi.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_119_1_oes.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_209_1_2U0.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_299_1_MUi.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_389_1_xuI.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_1_1_wJl.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_210_1_Jc3.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_300_1_QtY.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_390_1_md4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_120_1_vRm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_211_1_a6T.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_301_1_E0A.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_391_1_jun.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_121_1_U7E.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_21_1_AN8.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_30_1_cJ5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_39_1_TVp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_12_1_URa.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_212_1_Wyj.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_302_1_be8.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_392_1_1t7.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_122_1_0IM.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_213_1_z1U.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_303_1_xqK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_393_1_3NY.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_123_1_05u.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_214_1_hNp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_304_1_QJi.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_394_1_tar.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_124_1_hR8.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_215_1_Nzf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_305_1_gHD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_395_1_o3M.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_125_1_rr4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_216_1_UFw.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_306_1_5HL.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_396_1_Fv4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_126_1_4Sh.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_217_1_Q84.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_307_1_kVt.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_397_1_oqf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_127_1_oDW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_218_1_ood.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_308_1_ygd.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_398_1_irk.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_128_1_Bae.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_219_1_qDa.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_309_1_vjG.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_399_1_Alk.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_129_1_cEf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_2_1_Ags.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_310_1_JJq.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_400_1_xwl.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_130_1_VBE.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_220_1_Zjf.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_311_1_qzT.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_40_1_d92.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_131_1_PSB.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_221_1_mpV.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_31_1_YUt.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_41_1_fl5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_13_1_2Xi.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_22_1_h5e.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_312_1_tZK.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_4_1_5DD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_132_1_MSC.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_222_1_KmY.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_313_1_EIs.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_42_1_SYx.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_133_1_q9m.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_223_1_43Z.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_314_1_sam.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_43_1_Udu.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_134_1_RKJ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_224_1_7Fn.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_315_1_4zP.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_44_1_hgl.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_135_1_2Af.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_225_1_iEe.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_316_1_YT6.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_45_1_CB7.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_136_1_2md.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_226_1_NqQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_317_1_37V.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_46_1_Lj4.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_137_1_mGR.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_227_1_Jve.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_318_1_T9m.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_47_1_QM5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_138_1_sKO.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_228_1_Vbp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_319_1_tdA.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_48_1_zGF.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_139_1_vsu.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_229_1_3hG.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_3_1_ZNm.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_49_1_VBa.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_140_1_SKS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_230_1_93r.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_320_1_MgC.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_50_1_CtL.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_141_1_hC5.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_231_1_2vp.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_321_1_PpD.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_51_1_SaQ.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_14_1_vK3.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_23_1_BQO.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_32_1_BRa.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_5_1_Ugu.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_142_1_gzS.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_232_1_S7c.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_322_1_RKW.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_52_1_E6u.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_143_1_vWo.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_233_1_o80.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_323_1_d9o.root',
'file:/lustre/cms/store/user/calabria/Data/PAT2011/PAT_WH_ZH_TTH_HToTauTau_M-115_7TeV-pythia6-tauola_NoSkim/patTuple_53_1_mAO.root',

    )
)

process.particleListDrawer = cms.EDAnalyzer("ParticleListDrawer",
    	printOnlyHardInteraction = cms.untracked.bool(True),
    	maxEventsToPrint = cms.untracked.int32(-1),
    	src = cms.InputTag('genParticles')
  )

process.demoWH = cms.EDFilter("GenFilter",
	genParticles = cms.untracked.InputTag('genParticles'),
	#particles = cms.untracked.vdouble(24, -24),
	process = cms.untracked.int32(1),
    	filter = cms.bool(False)
)

process.demoTTH = cms.EDFilter("GenFilter",
	genParticles = cms.untracked.InputTag('genParticles'),
	#particles = cms.untracked.vdouble(6, -6),
	process = cms.untracked.int32(3),
    	filter = cms.bool(False)
)

process.demoZH = cms.EDFilter("GenFilter",
	genParticles = cms.untracked.InputTag('genParticles'),
	#particles = cms.untracked.vdouble(23),
	process = cms.untracked.int32(2),
    	filter = cms.bool(False)
)


process.p1 = cms.Path(process.demoWH
		     #* process.particleListDrawer
		     )

process.p2 = cms.Path(process.demoTTH 
		     #* process.particleListDrawer
		     )

process.p3 = cms.Path(process.demoZH
		     #* process.particleListDrawer
		     )

